# Upstreams point to container names in Docker network
upstream apiServer {
    server localhost:8000;       # your api container
}

upstream adminApiServer {
    server localhost:8001; # your admin-api container
}

server {
    listen 80;

    server_name localhost;

    # Route /api to api
    location /api/ {
        proxy_pass http://apiServer/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
    }

    # Route /admin-api to admin-api
    location /adminApi/ {
        proxy_pass http://adminApiServer/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
    }
}

